export const MESSAGES = 'messages'
export const CLOUD = 'cloud'
export const SERIES = 'series'
export const TOPICS = 'topics'

export const STORAGE_KEYVAL = 'keyval'
export const STORAGE_LOCAL = 'local'
export const STORAGE_SESSION = 'session'
export const STORAGE_DEXIE = 'dexie'
export const STORAGE_WINDOW = 'window'
